// Code generated by MockGen. DO NOT EDIT.
// Source: handler.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	fiber "github.com/gofiber/fiber/v2"
	gomock "github.com/golang/mock/gomock"
)

// MockBlogHandler is a mock of BlogHandler interface.
type MockBlogHandler struct {
	ctrl     *gomock.Controller
	recorder *MockBlogHandlerMockRecorder
}

// MockBlogHandlerMockRecorder is the mock recorder for MockBlogHandler.
type MockBlogHandlerMockRecorder struct {
	mock *MockBlogHandler
}

// NewMockBlogHandler creates a new mock instance.
func NewMockBlogHandler(ctrl *gomock.Controller) *MockBlogHandler {
	mock := &MockBlogHandler{ctrl: ctrl}
	mock.recorder = &MockBlogHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBlogHandler) EXPECT() *MockBlogHandlerMockRecorder {
	return m.recorder
}

// CreateBlog mocks base method.
func (m *MockBlogHandler) CreateBlog(c *fiber.Ctx) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBlog", c)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateBlog indicates an expected call of CreateBlog.
func (mr *MockBlogHandlerMockRecorder) CreateBlog(c interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBlog", reflect.TypeOf((*MockBlogHandler)(nil).CreateBlog), c)
}

// DeleteBlog mocks base method.
func (m *MockBlogHandler) DeleteBlog(c *fiber.Ctx) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBlog", c)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteBlog indicates an expected call of DeleteBlog.
func (mr *MockBlogHandlerMockRecorder) DeleteBlog(c interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBlog", reflect.TypeOf((*MockBlogHandler)(nil).DeleteBlog), c)
}

// GetAllBlogs mocks base method.
func (m *MockBlogHandler) GetAllBlogs(c *fiber.Ctx) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllBlogs", c)
	ret0, _ := ret[0].(error)
	return ret0
}

// GetAllBlogs indicates an expected call of GetAllBlogs.
func (mr *MockBlogHandlerMockRecorder) GetAllBlogs(c interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllBlogs", reflect.TypeOf((*MockBlogHandler)(nil).GetAllBlogs), c)
}

// GetBlogByID mocks base method.
func (m *MockBlogHandler) GetBlogByID(c *fiber.Ctx) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBlogByID", c)
	ret0, _ := ret[0].(error)
	return ret0
}

// GetBlogByID indicates an expected call of GetBlogByID.
func (mr *MockBlogHandlerMockRecorder) GetBlogByID(c interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBlogByID", reflect.TypeOf((*MockBlogHandler)(nil).GetBlogByID), c)
}

// UpdateBlog mocks base method.
func (m *MockBlogHandler) UpdateBlog(c *fiber.Ctx) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBlog", c)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateBlog indicates an expected call of UpdateBlog.
func (mr *MockBlogHandlerMockRecorder) UpdateBlog(c interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBlog", reflect.TypeOf((*MockBlogHandler)(nil).UpdateBlog), c)
}
