// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go

// Package mocks is a generated GoMock package.
package mocks

import (
	models "blog-api/internal/models"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockBlogRepo is a mock of BlogRepo interface.
type MockBlogRepo struct {
	ctrl     *gomock.Controller
	recorder *MockBlogRepoMockRecorder
}

// MockBlogRepoMockRecorder is the mock recorder for MockBlogRepo.
type MockBlogRepoMockRecorder struct {
	mock *MockBlogRepo
}

// NewMockBlogRepo creates a new mock instance.
func NewMockBlogRepo(ctrl *gomock.Controller) *MockBlogRepo {
	mock := &MockBlogRepo{ctrl: ctrl}
	mock.recorder = &MockBlogRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBlogRepo) EXPECT() *MockBlogRepoMockRecorder {
	return m.recorder
}

// CreateBlog mocks base method.
func (m *MockBlogRepo) CreateBlog(blog *models.Blog) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBlog", blog)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateBlog indicates an expected call of CreateBlog.
func (mr *MockBlogRepoMockRecorder) CreateBlog(blog interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBlog", reflect.TypeOf((*MockBlogRepo)(nil).CreateBlog), blog)
}

// DeleteBlog mocks base method.
func (m *MockBlogRepo) DeleteBlog(id *uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBlog", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteBlog indicates an expected call of DeleteBlog.
func (mr *MockBlogRepoMockRecorder) DeleteBlog(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBlog", reflect.TypeOf((*MockBlogRepo)(nil).DeleteBlog), id)
}

// GetAllBlogs mocks base method.
func (m *MockBlogRepo) GetAllBlogs() (*[]models.Blog, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllBlogs")
	ret0, _ := ret[0].(*[]models.Blog)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllBlogs indicates an expected call of GetAllBlogs.
func (mr *MockBlogRepoMockRecorder) GetAllBlogs() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllBlogs", reflect.TypeOf((*MockBlogRepo)(nil).GetAllBlogs))
}

// GetBlogByID mocks base method.
func (m *MockBlogRepo) GetBlogByID(id *uint) (*models.Blog, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBlogByID", id)
	ret0, _ := ret[0].(*models.Blog)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBlogByID indicates an expected call of GetBlogByID.
func (mr *MockBlogRepoMockRecorder) GetBlogByID(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBlogByID", reflect.TypeOf((*MockBlogRepo)(nil).GetBlogByID), id)
}

// UpdateBlog mocks base method.
func (m *MockBlogRepo) UpdateBlog(blog *models.Blog) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBlog", blog)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateBlog indicates an expected call of UpdateBlog.
func (mr *MockBlogRepoMockRecorder) UpdateBlog(blog interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBlog", reflect.TypeOf((*MockBlogRepo)(nil).UpdateBlog), blog)
}
