// Code generated by MockGen. DO NOT EDIT.
// Source: service.go

// Package mocks is a generated GoMock package.
package mocks

import (
	models "blog-api/internal/models"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockBlogService is a mock of BlogService interface.
type MockBlogService struct {
	ctrl     *gomock.Controller
	recorder *MockBlogServiceMockRecorder
}

// MockBlogServiceMockRecorder is the mock recorder for MockBlogService.
type MockBlogServiceMockRecorder struct {
	mock *MockBlogService
}

// NewMockBlogService creates a new mock instance.
func NewMockBlogService(ctrl *gomock.Controller) *MockBlogService {
	mock := &MockBlogService{ctrl: ctrl}
	mock.recorder = &MockBlogServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBlogService) EXPECT() *MockBlogServiceMockRecorder {
	return m.recorder
}

// CreateBlogService mocks base method.
func (m *MockBlogService) CreateBlogService(blog *models.Blog) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBlogService", blog)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateBlogService indicates an expected call of CreateBlogService.
func (mr *MockBlogServiceMockRecorder) CreateBlogService(blog interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBlogService", reflect.TypeOf((*MockBlogService)(nil).CreateBlogService), blog)
}

// DeleteBlogService mocks base method.
func (m *MockBlogService) DeleteBlogService(id *uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBlogService", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteBlogService indicates an expected call of DeleteBlogService.
func (mr *MockBlogServiceMockRecorder) DeleteBlogService(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBlogService", reflect.TypeOf((*MockBlogService)(nil).DeleteBlogService), id)
}

// GetAllBlogsService mocks base method.
func (m *MockBlogService) GetAllBlogsService() (*[]models.Blog, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllBlogsService")
	ret0, _ := ret[0].(*[]models.Blog)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllBlogsService indicates an expected call of GetAllBlogsService.
func (mr *MockBlogServiceMockRecorder) GetAllBlogsService() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllBlogsService", reflect.TypeOf((*MockBlogService)(nil).GetAllBlogsService))
}

// GetBlogByIDService mocks base method.
func (m *MockBlogService) GetBlogByIDService(id *uint) (*models.Blog, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBlogByIDService", id)
	ret0, _ := ret[0].(*models.Blog)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBlogByIDService indicates an expected call of GetBlogByIDService.
func (mr *MockBlogServiceMockRecorder) GetBlogByIDService(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBlogByIDService", reflect.TypeOf((*MockBlogService)(nil).GetBlogByIDService), id)
}

// UpdateBlogService mocks base method.
func (m *MockBlogService) UpdateBlogService(id *uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBlogService", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateBlogService indicates an expected call of UpdateBlogService.
func (mr *MockBlogServiceMockRecorder) UpdateBlogService(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBlogService", reflect.TypeOf((*MockBlogService)(nil).UpdateBlogService), id)
}
